### ISSUE TITLE
ArrayIndexOutOfBoundsException on line 498

### ISSUE THREAD

**Issue by davidvavra** [maltaisn/recurpickerlib#11]
Hi,
I see this crash in Crashlytics:

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at com.maltaisn.recurpicker.RecurrencePickerView$10.afterTextChanged(RecurrencePickerView.java:498)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9375)
       at android.widget.TextView.setText(TextView.java:5401)
       at android.widget.TextView.setText(TextView.java:5248)
       at android.widget.EditText.setText(EditText.java:113)
       at android.widget.TextView.setText(TextView.java:5205)
       at com.maltaisn.recurpicker.RecurrencePickerView.changeMode(RecurrencePickerView.java:639)
       at com.maltaisn.recurpicker.RecurrencePickerView$2.onClick(RecurrencePickerView.java:291)
       at android.view.View.performClick(View.java:6256)
       at android.view.View$PerformClick.run(View.java:24701)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6572)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

Not sure what the user was doing, he had Android 8

**Comment by maltaisn** [comment]
Here's the code that's causing the issue
```java
String[] parts = getResources().getQuantityString(formatId, freq)
        .replace("%d", "").split("\\|", 2);
freqLabel.setText(parts[0].trim());
freqEventLabel.setText(parts[1].trim());
```

Probably you or a translator forgot to add the `|` character in the translation of the `rp_format_day/week/month/year` strings. I checked my English and French strings, they're both correct.

Do you know what language the user is using?

**Comment by davidvavra** [comment]
Thanks, I found that the string in Lithuanian was missing |, fixed
